version: 0.1
phases:
  install:
    runtime-versions:
      docker: 18
      nodejs: 10

    commands:
      - npm i -g yarn
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      - export DOCKER_TAG=git-${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - docker build -t ${DOCKER_REGISTRY}/${DOCKER_REPO}:${DOCKER_TAG} .
      - docker tag ${DOCKER_REGISTRY}/${DOCKER_REPO}:${DOCKER_TAG} ${DOCKER_REGISTRY}/${DOCKER_REPO}:latest
      - docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}:${DOCKER_TAG}
      - docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}:latest
      - "printf '\ncommitref: %s\n' ${DOCKER_TAG} >> deployspec.yml"
